In [ ]:
import numpy as np

# Define the user-item interaction data
data = [
    [5, 3, 0, 1, 0],
    [4, 0, 0, 1, 0],
    [0, 2, 5, 0, 0],
    [0, 0, 0, 4, 5],
    [1, 1, 0, 5, 4]
]

# Create the user-item interaction matrix
user_item_matrix = np.array(data)
print("User-Item Interaction Matrix:")
print(user_item_matrix)

User-Item Interaction Matrix:
[[5 3 0 1 0]
 [4 0 0 1 0]
 [0 2 5 0 0]
 [0 0 0 4 5]
 [1 1 0 5 4]]


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Calculate cosine similarity between users
user_similarity = cosine_similarity(user_item_matrix)
print("User Similarity Matrix:")
print(user_similarity)


User Similarity Matrix:
[[1.         0.86091606 0.18832945 0.10559274 0.33510052]
 [0.86091606 1.         0.         0.1515108  0.33287702]
 [0.18832945 0.         1.         0.         0.05663655]
 [0.10559274 0.1515108  0.         1.         0.95265102]
 [0.33510052 0.33287702 0.05663655 0.95265102 1.        ]]


In [ ]:
def recommend_items(user_index, user_item_matrix, user_similarity):
    # Get the user's ratings
    user_ratings = user_item_matrix[user_index]

    # Calculate weighted scores for each item based on similarity and ratings
    scores = user_similarity[user_index].dot(user_item_matrix) / np.array([np.abs(user_similarity[user_index]).sum()])

    # Filter out already rated items
    scores[user_ratings > 0] = -np.inf

    # Recommend top N items
    recommended_indices = np.argsort(scores)[::-1][:3] # Top N recommendations
    return recommended_indices

# Example usage: Recommend items for User Index = 0 (User 1)
recommended_items = recommend_items(0, user_item_matrix, user_similarity)
print("Recommended Items for User Index = 0:", recommended_items)


Recommended Items for User Index = 0: [4 2 3]
